baseURL = "https://blog.mhashim6.me"
languageCode = "en"
title = "The Upside-Down Trees"
subtitle = "Blog, Timeless, Placeless by Muhammad Hashim (mhashim6)"
theme = "hugo-theme-ava"
paginate = 15
mainSections = "post"

[languages]
  [languages.en]
      languageName = "English"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    
[params]
  ga_id=""
  mainSections = ["post"]
  author = "mhashim6"
  header = "UpsideDownTrees"

  [params.meta_tags]
    meta_og_title = "The Upside-Down Trees"
    meta_description = "Blog, Timeless, Placeless by Muhammad Hashim (mhashim6)"
    meta_og_sitename = "blog.mhashim6.me"
    meta_og_type = "blog"
    meta_og_url = "https://blog.mhashim6.me"
    meta_og_image = "https://raw.githubusercontent.com/mhashim6/blog/main/static/images/default.jpeg"
    meta_og_description = "Blog, Timeless, Placeless by Muhammad Hashim (mhashim6)"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true   

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
    name = "Telegram"
    url = "https://t.me/UpsideDownTrees"
    weight = 1
    [menu.main.params]
        leaving = true

# [[menu.main]]
#     name = "Why?"
#     url = "/about/"
#     weight = 2

[[menu.main]]
    name = "About me?"
    url = "https://mhashim6.me"
    weight = 3
    [menu.main.params]
        leaving = true

[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
    [menu.main.params]
        leaving = false

[[menu.main]]
    name = "Archive"
    url = "/posts/"
    weight = 5

[permalinks]
  posts = "/:slug/"
  pages = "/:filename/"
