baseURL = "https://mhashim6.github.io/blog"
languageCode = "en"
title = "The Upside-Down Trees"
theme = "hugo-theme-ava"
paginate = 15
mainSections = "post"

[languages]
  [languages.en]
      languageName = "English"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
    
[params]
  ga_id=""
  mainSections = ["post"]
  

  [params.meta_tags]
    meta_description = "Muhammad Hashim (mhashim6)'s Blog"
    meta_og_title = "The Upside-Down Trees"
    meta_og_sitename = "The Upside-Down Trees"
    meta_og_type = "blog"
    meta_og_url = "https://blog.mhashim6.me"
    meta_og_image = "https://raw.githubusercontent.com/mhashim6/blog/main/static/images/default.jpeg"
    meta_og_description = "Muhammad Hashim (mhashim6)'s Timeless, Placeless Blog"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false
        pygmentsUseClasses = true
        pygmentsCodefences = true

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true   

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
    name = "Archive"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "Why?"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Website"
    url = "https://mhashim6.me"
    weight = 3

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
